# Generated by Django 5.2 on 2025-04-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_reservation_options_alter_table_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['table', 'reservation_time'], 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
    ]
